[package]
name = "vanity-address-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.30.0"
secp256k1 = { version = "0.27.0", features = ["rand"] }
rand = "0.8.5"
rayon = "1.7.0"
clap = { version = "4.3.0", features = ["derive"] }
hex = "0.4.3"
